### ISSUE TITLE
Mapped girls

### ISSUE THREAD

**Issue by mbabazigift** [UNFPAInnovation/GetIN-Web-2.0#1]
GIVEN that a DHO would want to view detailed information on the young pregnant girls being mapped within the district THEN he should be able to click on a provision in the side navigation menu, that when clicked will lead the user to a page with the relevant information. 

**Acceptance criteria**
+ The DHO should be able to filter through the information in the table based on a particular date they enter. 
+ The DHO should be able to filter through mapped girls by age in ascending order.
+ The DHO should be able to view the girl's personal details that were captured during the mapping process. 

**DoD**
+ The DHO should be able to view all the mapped girls in his district.

**Comment by mbabazigift** [comment]
According to the so far developed feature in the dashboard the following need to be added;
+ Sub-county of the girl.
+ Voucher ID.
+ DHO should be able to filter the girls by age.
+ Phone number of next of kin

**Comment by innyanzi** [comment]
- Sub-county of the girl added.

- Voucher ID added

- Filter girls age enabled

- Phone number of next of kin already exists

**Comment by mbabazigift** [comment]
- Capture date when the girl was mapped.
- Family planning methods are not reflecting on the dashboard.
- Risk assessment responses are not reflecting as well.
- Change dates of the menstruation date to; Date, Month, year.

**Comment by thenebbiking** [comment]
Hi @mbabazigift , 

- Point 1 above is fixed. 
- Point 2 is abit ambiguous. Could you add more details as to where / how they should show? Is this 
  in the table or?
- Point 3 is also ambiguous. Address like point 2 above. 
- Point 4 is fixed but doesnt this make it confusing since all other fields report the date as

**Comment by thenebbiking** [comment]
Point 4 is fixed but doesnt this make it confusing since all other fields report the date as 'Year'-
'Month'-'Day'. If so then i think we need to standardize this across the whole appliaction. We cant
have other places showing date as Date, Month, Year and others showing as Year, Month, Day.
Please choose one and lets work on implementing that across.

**Comment by mbabazigift** [comment]
@thenebbiking 

- Point 4; we need to standardize the date as Date, Month, Year across the application. though its already as Date, Month, Year for the mobile application and not the dashboard.
- Points 2 and 3; Are not reflecting any valid information. 
![Screenshot mapped girl](https://user-images.githubusercontent.com/53424064/70373289-d738c780-18f8-11ea-8618-0acdbb00c112.png)

**Comment by innyanzi** [comment]
![mapped_girs](https://user-images.githubusercontent.com/50903508/70531039-2edb6b00-1b65-11ea-8e5b-2c21d7f45bca.png)

**Comment by innyanzi** [comment]
@mbabazigift, please review and close if requirements are met.

**Comment by mbabazigift** [comment]
@innyanzi I have tested the new changes.

**Comment by mbabazigift** [comment]
@innyanzi  
Capture the details of the VHT or midwife that has mapped the young girl.
